version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  blog:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/blog
    env_file:
      - .env

volumes:
  mongodb_data:
