version: "3.8"
services:
  # Replica Set (required for Prisma Client)
  # https://stackoverflow.com/questions/76940883/nestjs-cant-connect-to-mongo-while-running-in-docker
  mongo:
    container_name: mongo
    build:
      dockerfile: mongo.Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27018
    # env_file:
    #   - .env
    ports:
      - "27018:27018"
    networks:
      - api

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - api

  blog:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: blog-app
    depends_on:
      - mongo
      - redis
    environment:
      DATABASE_URL: mongodb://root:prisma@mongo:27018/blog&directConnection=true
      REDIS_URL: redis
    # env_file:
    #   - .env
    networks:
      - api

volumes:
  mongodb_data:
  redis_data:

networks:
  api:
    driver: bridge
