version: "3.8"
services:
  # Replica Set (required for Prisma Client)
  # https://stackoverflow.com/questions/76940883/nestjs-cant-connect-to-mongo-while-running-in-docker
  mongo:
    container_name: mongo
    build:
      dockerfile: mongo.Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
    env_file:
      - .env
    ports:
      - "27018:27018"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
