const CACHE_TTL = 10800; // 3 hours
const REACT_QUERY_CACHE_TTL = 900; // 15 minutes
const REACT_QUERY_STALE_TTL = 600; // 10 minutes
const VALIDITY_THRESHOLD = 3550; // 1 hour - 10 seconds

export {
  CACHE_TTL,
  REACT_QUERY_CACHE_TTL,
  REACT_QUERY_STALE_TTL,
  VALIDITY_THRESHOLD,
};
